# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

r=float(input("enter the radius of circle"))
area=3.14*r*r
print("The area of circle with radius",r,"is",area)