# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

a=int(input("Enter the first number"))
b=int(input("Enter the second number"))
c=int(input("Enter the third number"))
avg=(a+b+c)/3
print("the average of the three numbers is",avg)