# -*- coding: utf-8 -*-
"""Mymodule.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

def greet(name):
  print("Hello,"+name,"welcome")
def add(a,b):
  return a+b

import mymodule_py as my

my.greet("Aadi")
my.add(2,8)