# -*- coding: utf-8 -*-
"""Encapsulation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaB5Zjt7cBnNdh0VAKuWtmRDgpduGb5Y
"""

#Encapsulation
class name:
  def __init__(self):
    self.var1 = "Aadi"
    self.__var2 = "Man"
  def Private(self):
    print(self.__var2)
obj = name()
print(obj.var1)
obj.Private()