# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

num=int(input("Enter a number" ))
if num%2==0:
 print("the number is even")
else:
  print("the number is odd")