# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXB0igobv_4S7lfjM5uapY95qoQlKt4A
"""

def factorial(n):
  if n < 0:
    return
  elif n == 0:
    return 1
  else:
    fact = 1
    for i in range(1, n + 1):
      fact *= i
    return fact
num = int(input("Enter a non-negative integer: "))
result = factorial(num)
print(f"The factorial of", num, "is", result)