# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iu2dUorxli0RnMGXYfUeFSkSlzn8VWjd
"""

a=int(input("enter start range"))
b=int(input("enter end range"))
fact=1
for i in range(1,5+1):
  fact*=i
  print(fact)