# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dr5gSgETCpcjqIKYAOnc9XMS05ZUTwL
"""

import math
angle=float(input("Enter the angle in degrees"))
radian=math.radians(angle)
print(f"sine of angle:,math.sin({radian})")
print(f"cosine of angle:,math.cos({radian})")