# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhB1nY3UK23XWMAI2nMtpPvytm6lpaaa
"""

for key, value in student.items():
      print(key, value)

Subject = {
    "Name"    : "Python",
    "Chapter" : "i",
    "Time"    : "j",
}
print(Subject)
for Time, j in Subject.items():
      print(Time, j)

