# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aw_psjuFoOiMAR4A8CDKZArA26Q8bfmQ
"""

list=[1,5,3,9,7]
list

#Sort
list.sort()
list
#Reverse
list.reverse()
list