# -*- coding: utf-8 -*-
"""Day4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

list=["dam",6,3,5]
list

#Accessing
print(list[2])

#Adding
#Using Append Function
list.append(6)
list

#Adding Using Insert Function
list.insert(2,9)
list

#Removing Using Remove Function
list.remove(3)
list

#Removing Using pop Function
list.pop(2)
list

#Length Function
len(list)

adi = [9,4,3,7,6,5,2,0]

#Sort Function
adi.sort()
adi

#Reverse Function
list.reverse()
list

#Iterating Through Function
for x in list:
    print(x)