# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhB1nY3UK23XWMAI2nMtpPvytm6lpaaa
"""

dict1 = {
    'a': 1,
    'b': 2
    }
dict2 = {
    'b': 3,
    'c': 4
    }
merged_dict = {**dict1, **dict2}
print("Merged Dictionary:", merged_dict)

