# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhB1nY3UK23XWMAI2nMtpPvytm6lpaaa
"""

def merged_list(list1,list2):
   newlist=list(set(list1+list2))
   return newlist
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
print(merged_list(list1,list2))