# -*- coding: utf-8 -*-
"""Inheritance.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaB5Zjt7cBnNdh0VAKuWtmRDgpduGb5Y
"""

class A:
  def feature1(self):
    print("Feature 1")

class B:
  def feature2(self):
    print("Feature 2")

class C(A, B):
  pass

obj = C()
obj.feature1()
obj.feature2()



