# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaB5Zjt7cBnNdh0VAKuWtmRDgpduGb5Y
"""

class Circle:
     def area(self):
        return 3.14 * self.radius ** 2
circle1=Circle()
circle1.radius=5
print(circle1.area())

