# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaB5Zjt7cBnNdh0VAKuWtmRDgpduGb5Y
"""

class Circle:
     def __init__(self,radius):
        self.radius = radius
     def area(self):
        return 3.14 * self.radius ** 2
circle1=Circle(4)
print(circle1.area())

