# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

a=input("Enter the number")
if a==a[::-1]:
 print("It is the palindrome")
else:
  print("It is not a palindrome")