# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TD8wKmOWPm1VWOEgz0nkdh5qwxOWJPOR
"""

class shapes:
  def area(self):
    pass
class Rectangle(shapes):
    def __init__(self,length,width):
       self.length=length
       self.width=width
    def area(self):
      return self.length*self.width
class Circle(shapes):
  def __init__(self,radius):
    self.radius=radius
  def area(self):
    return 3.14*self.radius*self.radius
shapes = [Rectangle(4,5),Circle(3)]
for i in shapes:
  print("Area : ",i.area())

