# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iu2dUorxli0RnMGXYfUeFSkSlzn8VWjd
"""

n=int(input("Enter the number"))
if n>0:
  print("It is a positive number")
elif n<0:
    print("The number is negative")
else:
      print("The number is zero")