# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXB0igobv_4S7lfjM5uapY95qoQlKt4A
"""

def is_prime(n):
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

def check_prime(n):
    if is_prime(n):
        print("Prime Number")
    else:
        print("Not a prime number")
check_prime(10)
check_prime(12)