# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYQihO_jhaD82AsOTMABjq3bxEoIJeNb
"""

#printing variables
a=1
b=2
print(a,b)

#printing String
print("Hello World")

#Formated string printing
a=5
b=7
print(f"first number{a} and second number{b} ")