# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhB1nY3UK23XWMAI2nMtpPvytm6lpaaa
"""

Subject = {
    "Name"    : "Python",
    "Chapter" : 5,
    "Time"    : "21hrs",
}
print(Subject)

print(Subject["Name"])

Subject["Time"]="35hrs"
Subject["Students"]=32
print(Subject)

del Subject["Chapter"]
print(Subject)