# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

a=float(input("enter the first number"))
b=float(input("enter the second number"))
operation=input("enter operation +,-,*,/")
if operation=="+":
 print("result",a+b)
elif operation=="-":
 print("result",a-b)
elif operation=="*":
 print("result",a*b)
elif operation=="/":
 print("result",a/b)
else:
 print("invalid operation")