# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

print("welcome to python programming!")

name = input("Enter your name")
print("Hello,",name, "welcome!")

a=int(input("Enter the first number"))
b=int(input("Enter the second number"))
print("The sum of",a,"and",b,"is",a+b)
print("The difference of",a,"and",b,"is",a-b)
print("The product of ",a,"and",b,"is",a*b)
print("The division result of",a,"and",b,"is",a/b)