# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXB0igobv_4S7lfjM5uapY95qoQlKt4A
"""

def sum_two_numbers(a, b):
  return a + b
num1 = 10
num2 = 5
result = sum_two_numbers(num1, num2)
print(f"The sum of {num1} and {num2} is {result}")