# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhB1nY3UK23XWMAI2nMtpPvytm6lpaaa
"""

tuple=("rama",1,0.58,9,7)
tuple

print(tuple[0])