# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYQihO_jhaD82AsOTMABjq3bxEoIJeNb
"""

def is_prime(num):
  if num<=0:
    return False
  for i in range(2,int(num**0.5)+1):
     if num%i==0:
       return False
       return True
number=int(input("enter a number:"))
if is_prime(number):
  print(f"{number}is a prime number.")
else:
  print(f"{number}is not a prime number.")